<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mappings [
        <!ELEMENT mappings (mapping)*>
        <!ELEMENT mapping (#PCDATA)>
        <!ATTLIST mapping
                path CDATA #REQUIRED
                bean CDATA #REQUIRED
                function CDATA #REQUIRED
                role (Anonymous|Normal|Admin) #IMPLIED
                validator CDATA #IMPLIED>
        ]>
<mappings>
    <mapping path="showLoginPage" bean="loginController" function="showLoginPage"></mapping>
    <mapping path="login" bean="loginController" function="login"></mapping>
    <mapping path="logout" bean="loginController" function="logout"></mapping>


    <mapping path="showCart" bean="shoppingCartController" function="getCartPage" role="Normal"></mapping>
    <mapping path="showCartData" bean="shoppingCartController" function="getCart" role="Normal"></mapping>

    <mapping path="addCartItem" bean="shoppingCartController" function="addItem" role="Normal"
             validator="addCartItemValidator"></mapping>
    <mapping path="delCartItem" bean="shoppingCartController" function="delItem" role="Normal"
             validator="comCartItemValidator"></mapping>
    <mapping path="incCartItem" bean="shoppingCartController" function="incItem" role="Normal"
             validator="comCartItemValidator"></mapping>
    <mapping path="decCartItem" bean="shoppingCartController" function="decItem" role="Normal"
             validator="comCartItemValidator"></mapping>

    <mapping path="addProductItem" bean="orderController" function="addProductItem" role="Anonymous"></mapping>
    <mapping path="showItemList" bean="orderController" function="getItemList" role="Anonymous"></mapping>

    <mapping path="createOrderFromCart" bean="orderController" function="createOrderFromCart"></mapping>
    <mapping path="showOrder" bean="orderController" function="showOrder" role="Anonymous"
             validator="showOrderValidator"></mapping>

    <mapping path="showAllCity" bean="addressController" function="getAllCityInfo"></mapping>
    <mapping path="showCity" bean="addressController" function="getCityInfo"></mapping>
</mappings>