<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mappings [
        <!ELEMENT mappings (mapping)*>
        <!ELEMENT mapping (#PCDATA)>
        <!ATTLIST mapping
                path CDATA #REQUIRED
                bean CDATA #REQUIRED
                function CDATA #REQUIRED
                role (Anonymous|Normal|Admin) #IMPLIED
                validator CDATA #IMPLIED>
        ]>
<mappings>
    <mapping path="getSystemUser" bean="loginController" function="getSystemUser"></mapping>
    <mapping path="showLoginPage" bean="loginController" function="showLoginPage"></mapping>
    <mapping path="login" bean="loginController" function="login"></mapping>
    <mapping path="logout" bean="loginController" function="logout"></mapping>


    <mapping path="showCart" bean="shoppingCartController" function="getCartPage"
             role="Normal"></mapping>
    <mapping path="showCartData" bean="shoppingCartController" function="getCart"
             role="Normal"></mapping>

    <mapping path="addCartItem" bean="shoppingCartController" function="addItem"
             role="Normal" validator="addCartItemValidator"></mapping>
    <mapping path="delCartItem" bean="shoppingCartController" function="delItem"
             role="Normal" validator="comCartItemValidator"></mapping>
    <mapping path="incCartItem" bean="shoppingCartController" function="incItem"
             role="Normal" validator="comCartItemValidator"></mapping>
    <mapping path="decCartItem" bean="shoppingCartController" function="decItem"
             role="Normal" validator="comCartItemValidator"></mapping>
    <mapping path="setCartItemCount" bean="shoppingCartController" function="setItemCount"
             role="Normal" validator="setCartItemValidator"></mapping>

    <mapping path="addProductItem" bean="orderController" function="addProductItem"
             role="Anonymous"></mapping>
    <mapping path="showItemList" bean="orderController" function="getItemList"
             role="Anonymous"></mapping>

    <mapping path="submitCart" bean="orderController" function="submitCart"
             role="Normal"></mapping>
    <mapping path="submitOrder" bean="orderController" function="submitOrder"
             role="Normal" validator="submitOrderValidator"></mapping>
    <mapping path="payOrder" bean="orderController" function="payOrder"
             role="Normal"></mapping>

    <mapping path="myHome" bean="orderController" function="getMyHomeInfo"
             role="Normal"></mapping>
    <mapping path="myOrders" bean="orderController" function="getMyOrders"
             role="Normal"></mapping>
    <mapping path="myUnCompleteOrders" bean="orderController" function="getMyUnCompleteOrders"
             role="Normal"></mapping>
    <mapping path="myCompleteOrders" bean="orderController" function="getMyCompleteOrders"
             role="Normal"></mapping>
    <mapping path="myOrderDetail" bean="orderController" function="getMyOrderDetail"
             role="Normal" validator="showOrderValidator">
    </mapping>

    <mapping path="showAllCity" bean="addressController" function="getAllCityInfo"></mapping>
    <mapping path="showCity" bean="addressController" function="getCityInfo"></mapping>
    <mapping path="getProvinces" bean="addressController" function="getProvinces"></mapping>
    <mapping path="getProvinceCities" bean="addressController" function="getProvinceCities"></mapping>
    <mapping path="getCityCountries" bean="addressController" function="getCityCountries"></mapping>

    <mapping path="getUserAddress" bean="addressController" function="getUserAddress"
             role="Normal"></mapping>
    <mapping path="addUserAddress" bean="addressController" function="addUserAddress"
             role="Normal"></mapping>
    <mapping path="delUserAddress" bean="addressController" function="delUserAddress"
             role="Normal"></mapping>
</mappings>