<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE validations[
        <!ELEMENT validations (properties*, validation+)>
        <!ATTLIST validations>

        <!ELEMENT properties (file+)>
        <!ATTLIST properties locale (US|FR|EN|SA|CN|TW|NL|AU|CA|GB|DE|IL|IN|IT|JP|KR|BR|ES|SE|TH) #REQUIRED>

        <!ELEMENT file (#PCDATA)>
        <!ATTLIST file >

        <!ELEMENT validation (rule)+>
        <!ATTLIST validation name NMTOKEN #REQUIRED>

        <!ELEMENT rule (param?,message)>
        <!ATTLIST rule
                fieldName NMTOKEN #IMPLIED
                type (required|int|double|email|expression|date|stringlength|url|creditcard|isbn|inetaddress) #REQUIRED>

        <!ELEMENT param EMPTY>
        <!ATTLIST param
                dateformat CDATA #IMPLIED
                expression CDATA #IMPLIED
                max NMTOKEN #IMPLIED
                min NMTOKEN #IMPLIED
                regex (true|false) "false">

        <!ELEMENT message (#PCDATA)>
        <!ATTLIST message
                key NMTOKEN #IMPLIED
                useAttributePlaceHolder (true|false) "false">
        ]>

<validations>

    <validation name="addCartItemValidator">
        <rule type="required" fieldName="itemId">
            <message>itemId is required</message>
        </rule>
        <rule type="stringlength" fieldName="itemId">
            <param min="1" max="10"/>
            <message useAttributePlaceHolder="true">itemId should be between ${min} and ${max}</message>
        </rule>
    </validation>

    <validation name="comCartItemValidator">
        <rule type="stringlength" fieldName="itemId">
            <param min="1" max="10"/>
            <message useAttributePlaceHolder="true">itemId should be between ${min} and ${max}</message>
        </rule>
    </validation>

    <validation name="setCartItemValidator">
        <rule type="stringlength" fieldName="itemId">
            <param min="1" max="10"/>
            <message useAttributePlaceHolder="true">itemId should be between ${min} and ${max}</message>
        </rule>
        <rule type="required" fieldName="itemCount">
            <message>itemCount is required</message>
        </rule>
        <rule type="int" fieldName="itemCount">
            <param min="1" max="10000"/>
            <message useAttributePlaceHolder="true">itemCount should be between ${min} and ${max}</message>
        </rule>
    </validation>

    <validation name="submitOrderValidator">
        <rule type="required" fieldName="payment">
            <message>payment is required</message>
        </rule>
        <rule type="int" fieldName="payment">
            <param min="1" max="100"/>
            <message useAttributePlaceHolder="true">payment should be between ${min} and ${max}</message>
        </rule>
        <rule type="required" fieldName="delivery">
            <message>delivery is required</message>
        </rule>
        <rule type="int" fieldName="delivery">
            <param min="1" max="100"/>
            <message useAttributePlaceHolder="true">delivery should be between ${min} and ${max}</message>
        </rule>
    </validation>

    <validation name="showOrderValidator">
        <rule type="required" fieldName="orderId">
            <message>orderId is required</message>
        </rule>
        <rule type="stringlength" fieldName="orderId">
            <param min="1" max="10"/>
            <message useAttributePlaceHolder="true">orderId stringlength should be between ${min} and ${max}</message>
        </rule>
    </validation>

</validations>